theme: minima
google_analytics: G-HGTXJ5KGEF
permalink: /:categories/:year/:month/:day/:title:output_ext

show_excerpts: false

header_pages:
  - about.md
  - portfolio.md
  
# generate social links in footer
minima:
  social_links:
    twitter: andrew_w_cloud
    github:  andrewwhitten
    linkedin: andrew-whitten-8835b8
  
title: Cloud Architecture
author: Andrew Whitten

comments:
  disqus:
    shortname: https-andrewwhitten-github-io-1
 
url: https://andrewwhitten.github.io

